title: Свой среди чужих
description: "Политота, сложные мемасы, немного про жизу в Штатах и прочее.\n\n
  I don't stand with Ukraine and I don't sponsor Ukrainian Nazi regime."
author:
  name: Свой среди чужих
  url: https://t.me/FriendToFoes

telegram: FriendToFoes
logo: /assets/logo.avif

social:
  name: Свой среди чужих
  links: 
    - https://t.me/FriendToFoes

webmaster_verifications:
  google: ekOruM39Wx-tNt9v3JCeluLzUCel73nkRQR6zb7SV1g
  yandex: c9ed39784726c129

url: https://friendtofoes.github.io
baseurl: ""
lang: ru

jekyll-mentions: https://t.me

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-github-metadata

sass:
  style: compressed

exclude:
  - README.md
